add_newline = true

[character]
success_symbol = "[➜](bold green)"

[username]
show_always = true
style_user = "#5c99ba"
style_root = "red bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "@[$hostname](#CF6C6E) in "


