command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

[volume]
label=VOL
instance=Master
interval=1
signal=10


[wifi]
instance=wlp3s0
interval=10
separator=true

[battery]
label=BAT
interval=30

[time]
command=date '+%d-%m-%Y %H:%M:%S'
interval=5
